name: Run tox

on: push

jobs:
  code-lint-test:
    name: tox tests
    runs-on: ubuntu-latest
    container: lisael/archtox

    steps:
      # Checkout the code which was pushed to Github
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install pylint and depdendencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      # Runs Python Unit Tests
      - name: Test Code
        run: make test
